# Site
repository: ajaysp04/ajaysp04.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ajay Singh Parmar
title: Senior Software Engineer
email: ajays.parmar04@gmail.com
website: https://ajaysp04.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: ajays_parmar
github_username:  ajaysp04
# stackoverflow_username: "ajay-s-parmar"
facebook_username: node.ajay
# flickr_username: jekyll
# dribbble_username: jekyll
instagram_username: ajay.sparmar
linkedin_username: ajay-singh-parmar

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Welcome to my corner of the web! I'm Ajay Singh Parmar, an experienced software engineer with a passion for crafting innovative solutions in web development, project management, and system architecture. With over 7 years of hands-on experience, I've navigated through diverse industries—from insurance to medical imaging to advertising technology—where I've led the development of cutting-edge applications, including a real-time bidder for an emerging ad platform.

  My journey has been defined by a commitment to driving projects to success, thriving in collaborative environments, and constantly seeking new challenges. Whether it's architecting scalable systems or spearheading development initiatives, I approach each project with a blend of creativity and technical expertise.

  My expertise is in web application development, mostly using <mark>Python</mark> and <mark>Golang</mark>. I have experience in <mark>GCP</mark> cloud and various databases including <mark>Postgres</mark>, <mark>MySQL</mark>, <mark>MongoDB</mark> and <mark>BigTable</mark>. Additionally, I have some experience in front-end technologies like React.js.

  Join me as I share insights, experiences, and the occasional code snippet on my journey through the dynamic world of software engineering. Let's explore the endless possibilities of technology together!

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Audiomob Limited
        link: https://audiomob.com/
        link_text: audiomob.com
        sub_title: Senior RTB Engineer
        caption: Feburary 2023 - Present
        location: Abu Dhabi, United Arab Emirates
        quote: >
          Monetize and connect with audiences in the perfect place... *in-game.*
        description: | # this will include new lines to allow paragraphs
          At Audiomob Limited, a pioneering company in the realm of in-game audio ads, I've been at the forefront of innovation, particularly in the development and deployment of our Real-Time Bidding (RTB) server. This involved overseeing every aspect from design to implementation, ensuring seamless integration with existing systems through collaboration with cross-functional teams including web development and R&D. 
          
          I took on the sole responsibility of designing the server architecture and implementing it using cutting-edge technologies like Golang, GCP, BigTable, and Redis caching, achieving remarkable low-latency responses of ~100ms for 99% of the 10 million daily ad requests. Leveraging the Gin Gonic framework for efficient development and deploying systems on GCP infrastructure, 
          I've successfully maintained the stability of the RTB server, ensuring smooth operation and reliability across all inventory from in-house SSPs.

      - layout: left
        title: Akamai Technologies
        link: https://www.akamai.com/
        link_text: akamai.com
        sub_title: Senior Software Engineer
        caption: March 2022 - October 2022
        quote: >
          Power and protect life online
        description: | # this will include new lines to allow paragraphs
          At Akamai Technologies, renowned for its cutting-edge content delivery network (CDN) solutions, I was deeply involved in enhancing network management tools and services. One of my key contributions was working on the design and implementation of scalable REST APIs features for the Router Configuration Management System, leveraging Flask. 

          Additionally, I developed and deployed a backend Database migration tool for RCM, streamlining developer workflows and enhancing the dynamic environment for developers and SQAs. Furthermore, I collaborated closely with DevOps and other teams to provide support, fix issues, and introduce new network management tools, showcasing my ability to thrive in a collaborative, cross-functional environment.

      - layout: left
        title: Adcuratio Media India Pvt. Ltd.
        link: https://adcuratio.com/
        link_text: adcuratio.com
        sub_title: Software Development Engineer 2
        caption: Feburary 2021 - March 2022
        quote: >
          Reimagine TV advertising with *National Custom Messaging*
        description: | # this will include new lines to allow paragraphs
            During my time at Adcuratio Media, I was immersed in innovative projects aimed at revolutionizing digital advertising. One significant accomplishment was architecting and developing a Multi-Seller Platform using event-driven design principles. I also spearheaded the creation of a real-time notification system and activity logger using Kafka and FastAPI. Additionally, I played a crucial role in designing and developing Subscriptions, Payments, and Reviews Services for Folksmedia Streaming service, utilizing Python, and providing mentorship to junior team members. 

            Furthermore, I contributed to the backend design of features for a complex Demand Side Platform (DSP) tailored for managing addressable advertising for agencies, further solidifying my expertise in the realm of digital advertising technology.

      - layout: left
        title: Meddiff Technologies Pvt. Ltd. (Now Ramsoft)
        link: https://www.ramsoft.com/
        link_text: ramsoft.com
        sub_title: Software Engineer
        caption: March 2019 - January 2021
        quote: >
          The all-in-one SaaS solution - *fast, innovative, customizable* - with *AI-powered imaging* and *instant access* to medical images for patients.
        description: | # this will include new lines to allow paragraphs
            At Meddiff Technologies (now Acquired by Ramsoft Technologies), I delved into groundbreaking projects aimed at enhancing healthcare technology. One notable achievement was developing a Quality Audit feature for the PACS server, elevating transparency and efficiency in Radiology. Moreover, I spearheaded the creation of an Anonymization system for DICOM images and Radiology Reports, facilitating seamless data sharing among over 20 Medical Universities. 

            Additionally, I played a pivotal role in the design, development, deployment, and installation of a Tele-ultrasound system using Django and ReactJS, empowering hospitals with advanced imaging capabilities.


      - layout: left
        title: Infosys Limited
        link: https://www.infosys.com/
        link_text: infosys.com
        sub_title: Senior System Engineer
        caption: November 2017 - Present
        quote: >
          Navigate Your Next to Evolve your Organization into an *AI-first Enterprise*
        description: | # this will include new lines to allow paragraphs
            At Infosys Limited, my first company, I embraced thrilling challenges, such as developing a policy change feature for underwriting processes of Universal Life and Whole Life insurance for a US-based client. Additionally, during my tenure, I contributed to various customer-facing applications, including a correspondence application and an insurance management portal. 

            Throughout these projects, I not only honed my technical skills but also learned invaluable lessons about software management and the skills essential for success in the software industry. This experience taught me about best practices and instilled in me the importance of continuous learning and adaptation in this dynamic field.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Jabalpur Engineerign College (JEC), Jabalpur
        caption: 2012 - 2016
        sub_title: Bachelor Of Engineering, Information Technology
        quote: >
          Jabalpur Engineering College, Jabalpur was established on 7 July, 1947 when the entire global chess board was witnessing a dramatic change.

          It was born just a few months before India broke the shackles of British slavery. This illustrious Institution got the distinction of being the Second Engineering College in India and is the premier institution of Engineering Education in Central India.
        description: | # this will include new lines to allow paragraphs
          During my time at JEC I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time at the university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Curiosity Club* and was also part of the training placement office as *Co-Ordinator* .

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in web application and software engineering some of my other interests and hobbies are:
      - Photography
      - Gaming
      - Knowning and Sharing about History and Cultures

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
